### ISSUE TITLE
BlockPlaceCertain Door

### ISSUE THREAD

**Issue by srthd** [fatpigsarefat/Quests#10]
door:
        type: "blockplacecertain"
        amount: 1
        block: 324

When I place an oak door, nothing happens.

**Comment by fatpigsarefat** [comment]
With the new version (v2.0.7-beta), you can try this in your config:
```yaml  
door:
    type: "blockplacecertain"
    amount: 1
    block: WOODEN_DOOR
    use-similar-blocks: true
```
